import base64

# This is a tiny 16x16 favicon
favicon_data = b'AAABAAEAEBAQAAEABAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAgAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAZ2dnAP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAERERERERERERERERERERERGjEaERMREREQMxAzERERERATEAMRERERERERERERERERMREzERERGQAxATERERESEQEhEREREREAARERERERERERERERIREBERERERERERERERERERERERERESISESERERERERERERERHwfwAA4AcAAMADAACAAQAAgAEAAAABAAAAAQAAAAEAAAABAAAAAAAAAAEAAAABAADAAQAAwAMAAOAHAAD4HwAA'
favicon_bytes = base64.b64decode(favicon_data)

with open('x:/smarty/static/img/favicon.ico', 'wb') as f:
    f.write(favicon_bytes)

print("Favicon created at x:/smarty/static/img/favicon.ico")